### PR TITLE
Expose internal classes and Injection Tokens

### LINKED ISSUE #183: Expose the auth0-angular classes for extension points
### Describe the problem you'd like to have solved

> Allow for the auth0-angular library to be more extensible/configurable for larger projects.

### Describe the ideal solution

* Expose required classes/angular structures to allow for an implementer to customize the usage of the library.
* Expose a testing suite that utilizes the newly exposed classes and other Angular tokens.
* Expose a secondary entry point that contains the mocked classes and test module.

## Alternatives and current work-arounds

> The only alternative has been to re-implement large chunks of the library.

### Additional context

I work on a series of applications that are currently in the process of implementing auth0. The library works well when auth0 is enabled and there is an SPA configured correctly.

Since the team I am on works in many UI applications that all share the same common library which holds our current authentication mechanism we have to be able to implement this authentication upgrade iteratively. We try to avoid long lived branches when possible.

We currently have a solution to do this; however, it was with a bit of effort to achieve this and the recent 1.6.0 release was not backwards compatible with 1.5.1 classes which is why I am now requesting this feature.

Much of the desire is to be able to dynamically change the dependency injection for the Auth0Client and AuthService when our legacy authentication is enabled to be able to take advantage of the AuthHttpInterceptor.

I do not mind submitting a PR with changes if this is something people would want.

As one last note, the auth0 community answer for testing when using this library leaves a lot to be desired. Ideally this solution will meet that need as well. https://community.auth0.com/t/how-to-unit-test-authservice-in-angular-sdk/52569/6

### PR DESCRIPTION
**Pull request by frederikprijck**
Exposes a few extra internal classes and Injection Tokens that could be useful for people to be able to access.

Closes #183

### CODE REVIEW

**Review by stevehobbsdev — APPROVED** [review]

**Comment by schnucks-pveeramach** [comment]
Hi, Is there an ETA for when this will be available in a release? We have a use case that requires us to retrieve the id token associated with an authorize call done using the non default audience. The idTokenClaims$ observable only gets events for the default audience it looks like.

**Comment by frederikprijck** [comment]
A release will most likely be done early next week, we are waiting on one fix that will go in this release.

That said, not sure this PR helps with what you are describing.

**Comment by schnucks-pveeramach** [comment]
Hmm, with the Auth0Client becoming public I was thinking we could do something like:
```
    this.authService.getAccessTokenSilently({
      audience: 'non default audience',
      ignoreCache: true
    }).pipe(take(1))
      .subscribe((token) => {
        auth0Client.getIdTokenClaims({ audience: 'non default audience' })
      });
```
Would that not be possible? If so, is there a better approach?

**Comment by frederikprijck** [comment]
This PR is not making `Auth0Client` **instance** public tho.
I believe what you are asking is not possible with our Angular SDK. Could you open an issue so we can look into supporting that ?

**Comment by schnucks-pveeramach** [comment]
Sure, created: https://github.com/auth0/auth0-angular/issues/214

**Pull request merged**
