### PR TITLE
Allow for angular versions after 14 and before 15 

### PR DESCRIPTION
**Pull request by kek-Sec**
fixes:
peer @angular/core@">=9 <=14" from @auth0/auth0-angular@1.10.0

`
npm ERR! Found: @angular/core@14.0.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^14.0.1" from the root project
npm ERR!   peer @angular/core@">=9 <=14" from @auth0/auth0-angular@1.10.0
npm ERR!   node_modules/@auth0/auth0-angular
npm ERR!     @auth0/auth0-angular@"1.10.0" from the root project
`

Allow for angular versions after 14 and before 15

### CODE REVIEW

**Comment by frederikprijck** [comment]
Thanks for the PR, can you elaborate why this change is needed?
This has never been an issue before, and we have always used the syntax `<= 13`, `<=12`, ...

Before merging this, I would like to understand why we need this change.

**Comment by kek-Sec** [comment]
Sure thing, I am trying to update the package and I'm getting a peer conflict based on the <=14 
I've got angular core and related libs on 14.0.1 , if I downgrade to 14.0.0 it works fine.

**Comment by frederikprijck** [comment]
That's weird. I just tried the following:

- create a new angular cli project
- ensure I am using 14.0.2

```
> ng update @angular/core@14.0.2 @angular/cli@14.0.2                                                                                                                        
Using package manager: npm
Collecting installed dependencies...
Found 22 dependencies.
Package '@angular/core' is already at '14.0.2'.
Package '@angular/cli' is already at '14.0.2'.
```

- Install @auth0/auth0-angular

```
> npm i @auth0/auth0-angular                                                                                                                                                   ✔  

added 9 packages, and audited 941 packages in 4s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Everything seems to work without any problem, I can install our SDK as well as include it in the application and run `ng build`.

Do the above steps work for you?

**Comment by kek-Sec** [comment]
I can confirm this is no longer a problem , could have had to do with npm , would still suggest merging to avoid future conflicts , tbh auth0 is the only lib that uses <=14 and not <=15

100% up to the team , cheers for the great work.

**Comment by frederikprijck** [comment]
Thanks for the PR, we explicitly opted for `<=14`, which shouldnt be any difference from this PR.

That said, Will close this as it doesnt solve anything.

**Pull request closed without merging**
