### PR TITLE
fix unit testing in interceptor

### PR DESCRIPTION
**Pull request by alexandre-melard**
remove the http and the domain from the request.url  if we are matching a path and not a full URI.
this will permit this kind of configuration:
```
AuthModule.forRoot({
  // The domain and clientId were configured in the previous chapter
  domain: 'yyy.eu.auth0.com',
  clientId: 'XXX',

  // Request this audience at user authentication time
  audience: 'https://yyy.eu.auth0.com/api/v2/',

  // Request this scope at user authentication time
  scope: 'read:current_user',

  // Specify configuration for the interceptor              
  httpInterceptor: {
    allowedList: [
      '/api/*',
      'http://mydomain.com/other/api/*',
      'https://mydomain.com/other/api/*',
      {
        // Match any request that starts 'https://beaucerons.eu.auth0.com/api/v2/' (note the asterisk)
        uri: 'https://beaucerons.eu.auth0.com/api/v2/*',
        tokenOptions: {
          // The attached token should target this audience
          audience: 'https://beaucerons.eu.auth0.com/api/v2/',

          // The attached token should have these scopes
          scope: 'read:current_user'
        }
      }
    ]
  }
})
```
I modified all interceptor test cases as they were false. request.url always contain the full URL including protocol and not only the path.

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by alexandre-melard** [comment]
Dear reviewer, I don't understand why smoke tests are failing... I have little spare time, do you prefer me to open an issue?
Or if you don't mind directing me?
Thanks for your help.

**Comment by frederikprijck** [comment]
@alexandre-melard .

Do not worry about the smoke tests. For security reasons, we do not allow executing them on forks.

I will review this PR soon, thanks for providing it.

Keep in mind, for future reference, we prefer opening an issue first.

**Review by frederikprijck — COMMENTED** [review]
Even though I believe this adds more flexibility, this could be a breaking change and will fail when people use the following config:

```
allowedList: [
  'foo.com/api'
]
```
I believe we don't want to make it the SDKs responsibility to decide what can and can not be stripped.

We could opt for using something like this:

```
allowedList: [
  '*foo.com/api*'
]
```
So that we can not add an asterix in the beginning and/or the end.

However, I am curious to understand why you need this feature? Is there any reason why you can not use the full domain? Or is there any reason why you can not use a uriMatcher?

```
allowedList: [
 {
      uriMatcher: (uri) => uri.indexOf('/api/contact') !== -1
  },
]
```

This would give you full control over the matching, without building something in the SDK that might work for you but not for others?

Given it is already available today (through the uriMatcher), I am not keen on adding the functionality added in this PR. However, open for further discussion if you strongly believe we should have this.

**Comment by alexandre-melard** [comment]
Hi Frederik,
Thank you very much for your feedback.
Actually I started to work following an online tutorial where they would show an example of :
```
allowedList: [
  '/api/*'
]
```
And this actually doesn't work, so I thought it was a missing feature...
I am happy to provide full uri, actually it's what I am doing now.
However I think the automatic tests are false because they are using only relative path instead of full URI which can lead to misunderstandings.

Have a good day and thanks again for your time, I appreciate your directions on uriMatcher, I didn't notice we could use that.

Best Regards,
Alexandre

**Comment by frederikprijck** [comment]
Hey @alexandre-melard ,

Could you point me to the tutorial that has this incorrect example? That would be very helpful.

> However I think the automatic tests are false because they are using only relative path instead of full URI which can lead to misunderstandings.

I understand how those can be confusing. However, it will need a bit more changes to the tests when we are not going to strip the domain. Would you like to update this PR to drop the domain stripping and focus on only fixing the tests?

If not, no worries. I am happy to fix.

**Comment by alexandre-melard** [comment]
Hi @frederikprijck 
Done.
Alexandre

**Comment by frederikprijck** [comment]
Thanks for the fast update, this fails the test because we also need to update the config here https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.interceptor.spec.ts#L60-L95.

**Comment by frederikprijck** [comment]
I pushed a commit to the PR to fix the tests.

**Pull request merged**
